### ISSUE TITLE
Reports an undefined for buyQuantity with Interactive brokers trade confirmation statement

### ISSUE THREAD

**Issue by katravai** [Eleven-Trading/TradeNote#12]
![image](https://user-images.githubusercontent.com/121401602/221220372-bb4a0faf-0f4a-4cd3-955c-60e80e0eb86f.png)

**Comment by 7aklhz** [comment]
Thanks for trying out Tradenote. 

This is most probably due to the fact that you're not importing the correct format or that you have not chosen "Interactive Brokers" in the dropdown list. I suggest you check out the [discord](https://discord.gg/ZbHekKYb85) channel to see the history of chat around this subject.
