### ISSUE TITLE
IBKR Imports missing Symbol

### ISSUE THREAD

**Issue by cainfe** [Eleven-Trading/TradeNote#78]
When I import trades from Interactive Brokers following the instructions in brokers. My trades import with their Symbols being blank. Looking at the CSV, the column for "UnderlyingSymbol" has blank data and the column for "Symbol" has the right data, if I switch their names (so that the previously named "Symbol" column becomes "UnderlyingSymbol") it imports correctly. 

I think the line here https://github.com/Eleven-Trading/TradeNote/blob/6fff5826e61db88b5a5bf820011ba105894c9591/src/utils/brokers.js#L618 would need to be changed. I just started using IBKR and I only trade stocks and I'm not exactly sure how this comes into play.

**Comment by HadronUA** [comment]
I have the same issue, but for the futures it works correct(for example you want to see CL(UnderlyingSymbol) instead of CLH4(Symbol)), because Symbol changes every month and you want to see the whole statictics.
I think it would be nice to add something like this here:
https://github.com/Eleven-Trading/TradeNote/blob/6fff5826e61db88b5a5bf820011ba105894c9591/src/utils/brokers.js#L597C21-L597C25

line 597
                    temp.Type = "stock"
                    temp.Symbol = element["Symbol"]
                    if (element.AssetClass == "FUT") {
                        temp.Type = "future"
                        temp.Symbol = element["UnderlyingSymbol"] 
                    }

**Comment by 7aklhz** [comment]
@cainfe @HadronUA : can we please move this conversation to Discord ? I need more infos + make tests. Please ping me when on Discord.

**Comment by HadronUA** [comment]
@7aklhz ok. My Discord username is hadronua.

**Comment by 7aklhz** [comment]
I don't see you on our discord @HadronUA . Please connect to https://discord.gg/ZbHekKYb85

**Comment by cainfe** [comment]
Resolved in commit 78280125bbbe9fd42b3fc75fde031ad9ba11efda.
